version: 1.1.{build}
branches:
  only:
  - master
install:
- cmd: git submodule update -q --init
build_script:
- ps: >-
    # stage files (including submodules) in 'archive' directory for artifact creation
    git checkout-index -q -a --prefix="archive/";
    git submodule foreach 'git checkout-index -q -a --prefix="$toplevel/archive/$path/"';

    # create bin directory for script(s) to modify diff output in Git Bash
    New-Item -ItemType "Directory" -Path "archive\bin" | Out-Null;

    # script for colorizing diff output in Git Bash
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/git/git/master/contrib/diff-highlight/diff-highlight" -OutFile "archive\diff-highlight";
test_script:
- ps: >-
    # check existence of required directories for zip artifact creation
    ForEach ($RequiredPath in @( "archive", "archive\bin", "archive\.vim" ))
    {
        If (Test-Path -Path $RequiredPath -PathType Container)
        {
            Write-Host "Found required '$($Path)' path for artifact creation.";
        }
        Else
        {
            Throw "Can't find required '$($Path)' path for artifact creation. $_";
        }
    }
artifacts:
- path: archive
  name: $($env:APPVEYOR_PROJECT_NAME)-$($env:APPVEYOR_BUILD_VERSION)
