version: 1.0.{build}
install:
- cmd: git submodule update -q --init
build_script:
- ps: >-
    # stage files in 'latest' folder for zip artifact creation

    git checkout-index -q -a --prefix="latest/"

    # also stage files from submodules

    git submodule foreach 'git checkout-index -q -a --prefix="$toplevel/latest/$path/"'
test_script:
- ps: >-
    # check existence of path for zip artifact creation

    $ArchivePath = "$($env:APPVEYOR_BUILD_FOLDER)\latest";

    If (Test-Path -Path $($ArchivePath) -PathType Container)
    {
        Write-Host "Found $($ArchivePath) for artifact creation.";
    }
    Else
    {
        Throw "Can't find $($ArchivePath) path for artifact creation. $_";
    }
artifacts:
- path: latest
  name: dotfiles-latest
