version: 1.1.{build}
branches:
  only:
  - master
install:
- cmd: git submodule update -q --init
build_script:
- ps: >-
    # create bin directory for script(s) to modify diff output in Git Bash

    New-Item -ItemType "Directory" -Path "bin" | Out-Null;


    # script for colorizing diff output in Git Bash

    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/git/git/master/contrib/diff-highlight/diff-highlight" -OutFile "diff-highlight";
test_script:
- ps: >-
    # check existence of required top-level directories

    ForEach ($RequiredPath in @( "bin", ".vim" ))

    {

        If (Test-Path -Path $RequiredPath -PathType Container)

        {

            Write-Host "Found required '$($Path)' path for release.";

        }

        Else

        {

            Throw "Can't find required '$($Path)' path for release. $_";

        }

    }
artifacts:
- path: .
  name: $($env:APPVEYOR_PROJECT_NAME)-$($env:APPVEYOR_BUILD_VERSION)
