- name: Setup local workstation
  hosts: workstation
  roles:
    - role: bash
      tags:
        - bash
    - role: git
      tags:
        - git
    - role: vim
      tags:
        - vim
    - role: zsh
      tags:
        - zsh
